### ISSUE TITLE
About MAP

### ISSUE THREAD

**Issue by wulele2** [lishuhuai527/COCO-UniHuman#2]
Hello, I downloaded your data and loaded the weight, but the AP measured does not match your paper, please see where the problem is。I measured the results:
My AP_medium and AP_large are basically the same as in the paper, but the value of AP does not correspond to the paper.

`loading annotations into memory...
Done (t=0.46s)
creating index...
index created!
===== [Task info] =====
with_kp: True
with_det: True
with_seg: True
with_attr: True
with_smpl: True
load checkpoint from local path: workdir/human_query_net_all_task_r50_scratch/HumanQueryNet_r50.pth
[                                                  ] 0/2693, elapsed: 0s, ETA:/opt/conda/envs/HQN/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2693/2693, 3.6 task/s, elapsed: 749s, ETA:     0s
Evaluating age...
Loading and preparing results...
DONE (t=1.43s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=4.89s).
Accumulating evaluation results...
DONE (t=2.23s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.618
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.570
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.380
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.604
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.799
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.799
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.799
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.726
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.839

Evaluating gender...
Loading and preparing results...
DONE (t=0.87s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=5.56s).
Accumulating evaluation results...
DONE (t=2.29s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.538
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.635
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.585
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.611
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.818
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.818
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.818
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.746
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.858

Loading and preparing results...
DONE (t=7.24s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=12.33s).
Accumulating evaluation results...
DONE (t=0.41s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.688
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.891
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.763
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.637
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.773
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.763
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.929
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.824
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.707
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.842

mpjpe_gt_smpl54_pred_smpl54_with_gender  :87.79  54.58
mpjpe_gt_smpl54_pred_h36m_with_gender    :98.24  61.86
mpjpe_gt_smpl54_pred_smpl54_neutral      :84.63  55.04
mpjpe_gt_smpl54_pred_h36m_neutral        :95.43  62.15
mpjpe_gt_h36m_pred_smpl54_with_gender    :101.08  65.89
mpjpe_gt_h36m_pred_h36m_with_gender      :85.50  50.97
mpjpe_gt_h36m_pred_smpl54_neutral        :101.06  67.33
mpjpe_gt_h36m_pred_h36m_neutral          :82.35  51.45

Evaluating bbox...
Loading and preparing results...
DONE (t=1.48s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=18.70s).
Accumulating evaluation results...
DONE (t=7.48s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.628
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.840
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.702
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.433
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.704
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.800
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.759
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.759
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.759
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.632
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.806
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.897

Evaluating segm...
/opt/conda/envs/HQN/lib/python3.8/site-packages/mmdet/datasets/coco.py:470: UserWarning: The key "bbox" is deleted for more accurate mask AP of small/medium/large instances since v2.12.0. This does not change the overall mAP calculation.
  warnings.warn(
Loading and preparing results...
DONE (t=3.13s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=24.10s).
Accumulating evaluation results...
DONE (t=8.24s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.531
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.826
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.598
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.312
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.585
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.734
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.640
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.640
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.640
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.495
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.689
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.802

{'age_mAP': 0.525, 'age_mAP_50': 0.618, 'age_mAP_75': 0.57, 'age_mAP_s': -1.0, 'age_mAP_m': 0.38, 'age_mAP_l': 0.604, 'age_mAP_copypaste': '0.525 0.618 0.570 -1.000 0.380 0.604', 'gender_mAP': 0.538, 'gender_mAP_50': 0.635, 'gender_mAP_75': 0.585, 'gender_mAP_s': -1.0, 'gender_mAP_m': 0.405, 'gender_mAP_l': 0.611, 'gender_mAP_copypaste': '0.538 0.635 0.585 -1.000 0.405 0.611', 'mpjpe_gt_smpl54_pred_smpl54_with_gender': 87.79346, 'pa_mpjpe_gt_smpl54_pred_smpl54_with_gender': 54.579827166240904, 'mpjpe_gt_smpl54_pred_h36m_with_gender': 98.24139, 'pa_mpjpe_gt_smpl54_pred_h36m_with_gender': 61.857801669271524, 'mpjpe_gt_smpl54_pred_smpl54_neutral': 84.62819, 'pa_mpjpe_gt_smpl54_pred_smpl54_neutral': 55.044806299945414, 'mpjpe_gt_smpl54_pred_h36m_neutral': 95.43283, 'pa_mpjpe_gt_smpl54_pred_h36m_neutral': 62.15483071799204, 'mpjpe_gt_h36m_pred_smpl54_with_gender': 101.08316, 'pa_mpjpe_gt_h36m_pred_smpl54_with_gender': 65.88982564900326, 'mpjpe_gt_h36m_pred_h36m_with_gender': 85.49736, 'pa_mpjpe_gt_h36m_pred_h36m_with_gender': 50.967736293393735, 'mpjpe_gt_h36m_pred_smpl54_neutral': 101.063934, 'pa_mpjpe_gt_h36m_pred_smpl54_neutral': 67.3312364190776, 'mpjpe_gt_h36m_pred_h36m_neutral': 82.35339, 'pa_mpjpe_gt_h36m_pred_h36m_neutral': 51.45030957918311, 'bbox_mAP': 0.628, 'bbox_mAP_50': 0.84, 'bbox_mAP_75': 0.702, 'bbox_mAP_s': 0.433, 'bbox_mAP_m': 0.704, 'bbox_mAP_l': 0.8, 'bbox_mAP_copypaste': '0.628 0.840 0.702 0.433 0.704 0.800', 'segm_mAP': 0.531, 'segm_mAP_50': 0.826, 'segm_mAP_75': 0.598, 'segm_mAP_s': 0.312, 'segm_mAP_m': 0.585, 'segm_mAP_l': 0.734, 'segm_mAP_copypaste': '0.531 0.826 0.598 0.312 0.585 0.734'}`

**Comment by jin-s13** [comment]
As stated in our paper, we report AP for the “Person” category without **_Small_** category person.

**Comment by wulele2** [comment]
Thank you for your reply.

**Comment by lishuhuai527** [comment]
As @jin-s13 explained, our AP stands for AP without **_Small_**. 
To get AP without small, please backup and modify yourcondahome/envs/HQN/lib/python3.9/site-packages/pycocotools/cocoeval.py:
modify the areaRng of 'all' from [0 ** 2, 1e5 ** 2] to [32 ** 2, 1e5 ** 2] in both setDetParams() and setKpParams().

In addition, HumanQueryNet_r50_DSPC.pth is available now, which can recurrence the results of HQNet (D+S+P+C) in Table2.
